'use strict';

/**
 * What makes a vibration line that is no multiple of rotor speed: <dir>/line.json (line.cjs) -> <dir>/line_report.md
 *
 *   node tools/autotune/line_report.cjs <dir>
 *
 * Every candidate source leaves a different fingerprint in the log. The report measures each fingerprint and says
 * which candidates survive. It cannot see inside the helicopter: what survives is a statement about the data, and the
 * bench test at the end decides.
 */

const fs = require('node:fs'), path = require('node:path');

const RULES = {
    snr: { line: 10, main: 5 },       // a window counts when the line and the main rotor line stand this far above their surroundings
    short: { line: 5, main: 3 },
    groups: [['21 Sep (#0–#5)', 0, 5], ['#6', 6, 6], ['#7–#16', 7, 16], ['#17–#26', 17, 26]], // from the pilot: carbon tail blades from #17
    ratios: [[72, 19], [76, 19], [76, 20], [91, 24], [53, 14]], // small-number ratios near the line
    collectiveBins: [-300, -100, 100, 300], tailCentre: 775, logLimitHz: 497,
    rollerTolerance: 0.004,           // relative spread of a tensioner roller's effective diameter (±0.05 mm on about 12.8 mm)
};

const DIR = process.argv[2];
if (!DIR) { console.error('usage: node line_report.cjs <dir with line.json>'); process.exit(2); }
const L = JSON.parse(fs.readFileSync(path.join(DIR, 'line.json'), 'utf8'));
const B = fs.existsSync(path.join(DIR, 'bursts.json')) ? JSON.parse(fs.readFileSync(path.join(DIR, 'bursts.json'), 'utf8')) : null;

const n = (v, d = 1) => (typeof v === 'number' && isFinite(v)) ? v.toFixed(d) : '–';
const quantile = (a, p) => { if (!a.length) return NaN; const s = [...a].sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };
const median = (a) => quantile(a, 0.5), sum = (a) => a.reduce((s, v) => s + v, 0);
const table = (head, rows) => ['| ' + head.join(' | ') + ' |', '|' + head.map(() => '---').join('|') + '|', ...rows.map(r => '| ' + r.join(' | ') + ' |'), ''];
const amp = (axes) => Math.hypot(...axes.map(c => Math.hypot(c[0], c[1])));
const groupOf = (log) => (RULES.groups.find(([, a, b]) => log >= a && log <= b) || ['other'])[0];
function spearman(x, y) {
    const rank = (a) => { const idx = a.map((v, i) => i).sort((i, j) => a[i] - a[j]), r = new Array(a.length); idx.forEach((i, k) => { r[i] = k; }); return r; };
    const u = rank(x), v = rank(y), m = u.length, mu = (m - 1) / 2; let a = 0, b = 0, c = 0;
    for (let i = 0; i < m; i++) { a += (u[i] - mu) * (v[i] - mu); b += (u[i] - mu) ** 2; c += (v[i] - mu) ** 2; }
    return a / Math.sqrt(b * c);
}
// the ratio of the line to the main rotor line: per window, then per log, with the standard error between logs
const ratio = (w) => w.line.order / w.main.order;
function stat(list) {
    const logs = [...new Set(list.map(w => w.log))], per = logs.map(l => { const x = list.filter(w => w.log === l).map(ratio); return sum(x) / x.length; });
    const m = sum(per) / per.length, se = per.length > 1 ? Math.sqrt(sum(per.map(v => (v - m) ** 2)) / (per.length - 1) / per.length) : NaN;
    return { windows: list.length, logs: logs.length, mean: m, se, p10: quantile(list.map(ratio), 0.1), p90: quantile(list.map(ratio), 0.9), amplitude: median(list.map(w => amp(w.line.axes))) };
}
const statRow = (label, s) => [...label, s.windows, s.logs, n(s.mean, 5), n(s.se, 5), `${n(s.p10, 4)} – ${n(s.p90, 4)}`, n(s.amplitude, 1)];
const statHead = ['Windows', 'Logs', 'Ratio to main rotor', '± (between logs)', '10–90 % of windows', 'Line size, median (deg/s)'];

const long = L.windows.filter(w => w.pass === 'long' && w.line.snr >= RULES.snr.line && w.main.snr >= RULES.snr.main);
const short = L.windows.filter(w => w.pass === 'short' && w.line.snr >= RULES.short.line && w.main.snr >= RULES.short.main);
const all = stat(long), target = all.mean;
const out = [], results = { rules: RULES };
const H = (s) => out.push(s, '');

H('# The vibration line near 3.79 × rotor speed');
H(`Source: \`${L.file}\`. Generated by \`tools/autotune/line_report.cjs\` from \`line.json\` (\`tools/autotune/line.cjs\`); thresholds in \`RULES\` at the top of the script.`);

H('## 1. How it is measured');
out.push(`The raw gyro is resampled at equal steps of rotor angle (${L.rule.perRev} per revolution of the logged headspeed) and cut into windows of ${L.rule.passes[0].revolutions} revolutions (${L.rule.passes[1].revolutions} for short stays and the ground). ` +
    'In each window the line, the main rotor\'s once-per-revolution line and the line near 4 × are located to a fraction of a bin. ' +
    'The ratio of the line to the main rotor line in the same window is independent of any error in the headspeed reading and of the logging clock.', '');
out.push(`${long.length} long windows qualify (line ${RULES.snr.line} times, main line ${RULES.snr.main} times above their surroundings), from ${new Set(long.map(w => w.log)).size} logs.`, '');

H('## 2. The ratio');
const near = RULES.ratios.map(([p, q]) => ({ p, q, v: p / q, sigmas: Math.abs(p / q - all.mean) / all.se }));
results.ratio = { mean: all.mean, se: all.se, windows: all.windows, logs: all.logs, candidates: near };
out.push(`All long windows: **${n(all.mean, 5)} ± ${n(all.se, 5)}** × the main rotor line (standard error between ${all.logs} logs). Nearby ratios of small whole numbers, and how far each lies from the measurement in standard errors:`, '');
out.push(...table(['Ratio', 'Value', 'Standard errors away'], near.map(c => [`${c.p}/${c.q}`, n(c.v, 5), n(c.sigmas, 1)])));
const tail = L.windows.filter(w => w.pass === 'long' && w.tail.snr >= 5 && w.main.snr >= RULES.snr.main), tailRatio = tail.map(w => w.tail.order / w.main.order);
results.tailLine = { windows: tail.length, median: median(tailRatio), p10: quantile(tailRatio, 0.1), p90: quantile(tailRatio, 0.9) };
const four = stat(tail.map(w => Object.assign({}, w, { line: w.tail })));  // the same statistics, for the line at 4 ×
const both = long.filter(w => w.tail.snr >= 5), against = stat(both.map(w => Object.assign({}, w, { main: w.tail })));
results.calibration = { fourLine: { mean: four.mean, se: four.se, logs: four.logs }, againstFour: { mean: 4 * against.mean, se: 4 * against.se, logs: against.logs } };
out.push(`A second, smaller line sits at 4 × the main rotor, as the configured 76:19 tail drive gives. Being an exact multiple whatever makes it, it checks the method: measured the same way it comes out at ${n(four.mean, 5)} ± ${n(four.se, 5)} (${four.logs} logs). ` +
    `Measured against that line instead of the main rotor line, in the ${both.length} windows that have both, the big line lies at ${n(4 * against.mean, 5)} ± ${n(4 * against.se, 5)} × the main rotor, ${n(Math.abs(4 * against.mean - 72 / 19) / (4 * against.se), 1)} standard errors from 72/19. ` +
    'The method is good to about 1 part in 10,000; within that, the line is at 72/19 and at none of the other ratios.', '');

H('## 3. Does the ratio move?');
out.push('A part turned through teeth keeps its ratio whatever happens. A part turned by friction creeps as the load on it changes. A ball bearing\'s ball-pass frequency moves with its contact angle, which follows the axial load. A blade or rotor mode that scales with rotor speed moves when the blades change.', '');
out.push('**By group of flights and PID profile** (the pilot changed to carbon tail blades from #17):', '');
out.push(...table(['Group', 'Profile', ...statHead], RULES.groups.flatMap(([g]) => [0, 1, 2, 3].map(p => { const list = long.filter(w => groupOf(w.log) === g && w.profile === p); return list.length >= 3 ? statRow([g, p || 'as armed'], stat(list)) : null; })).filter(Boolean)));
const cb = RULES.collectiveBins, bins = [-Infinity, ...cb, Infinity];
out.push('**By collective**, mean over the window (setpoint units, full range ±1250):', '');
out.push(...table(['Collective', ...statHead], bins.slice(0, -1).map((lo, i) => { const hi = bins[i + 1], list = long.filter(w => w.collective >= lo && w.collective < hi); return list.length >= 3 ? statRow([`${lo === -Infinity ? 'below' : lo} … ${hi === Infinity ? 'above' : hi}`], stat(list)) : null; }).filter(Boolean)));
const servo = long.filter(w => w.tailServo !== null), cuts = [0.25, 0.5, 0.75].map(p => quantile(servo.map(w => w.tailServo), p));
out.push('**By tail servo position**, quarters of all windows:', '');
out.push(...table(['Tail servo (µs, median)', ...statHead], [0, 1, 2, 3].map(q => { const list = servo.filter(w => cuts.filter(c => w.tailServo >= c).length === q); return statRow([n(median(list.map(w => w.tailServo)), 0)], stat(list)); })));
out.push(`**On the ground and in the air** (short windows of ${L.rule.passes[1].revolutions} revolutions):`, '');
out.push(...table(['Where', ...statHead, 'Headspeed (rpm, median)'], [['on the ground', (w) => w.airborne < 0.05], ['in the air', (w) => w.airborne > 0.95]].map(([name, test]) => { const list = short.filter(test); return [...statRow([name], stat(list)), n(median(list.map(w => w.headspeed)), 0)]; })));
const spread = (list) => { const s = list.map(stat).filter(v => v.windows >= 10); return Math.max(...s.map(v => v.mean)) - Math.min(...s.map(v => v.mean)); };
const moves = { blades: Math.abs(stat(long.filter(w => groupOf(w.log) === '#17–#26' && w.profile === 1)).mean - stat(long.filter(w => groupOf(w.log) === '#7–#16' && w.profile === 1)).mean),
    collective: spread(bins.slice(0, -1).map((lo, i) => long.filter(w => w.collective >= lo && w.collective < bins[i + 1]))), servo: spread([0, 1, 2, 3].map(q => servo.filter(w => cuts.filter(c => w.tailServo >= c).length === q))) };
results.moves = moves;
out.push(`Largest change of the ratio between conditions: blade change ${n(moves.blades, 5)} (profile 1), collective ${n(moves.collective, 5)}, tail servo ${n(moves.servo, 5)}; that is ${n(1e6 * Math.max(moves.blades, moves.collective, moves.servo) / target, 0)} parts per million at most.`, '');

H('## 4. Other fingerprints');
const spectra = L.spectra, R = spectra[0].revolutions, nb = spectra[0].m.length / 9;
const pool = (test) => { const list = spectra.filter(test), m = new Float64Array(nb * 9); let w = 0; for (const e of list) { for (let i = 0; i < e.m.length; i++) m[i] += e.m[i]; w += e.windows; } return { m, w }; };
const scaleOf = median(long.map(w => w.main.order));  // where the main rotor line sits against the logged headspeed
const P = (m, k) => m[9 * k] + m[9 * k + 1] + m[9 * k + 2];
function lineAt(m, w, order) { const k0 = Math.round(order * scaleOf * R); let b = k0; for (let k = k0 - 2; k <= k0 + 2; k++) if (P(m, k) > P(m, b)) b = k;
    const around = []; for (let k = k0 - 40; k <= k0 + 40; k++) if (Math.abs(k - k0) > 4) around.push(P(m, k)); around.sort((x, y) => x - y);
    return { axes: [0, 1, 2].map(a => Math.sqrt(m[9 * b + a] / w)), stands: Math.sqrt(P(m, b) / around[around.length >> 1]) }; }
const low = RULES.groups.slice(2).map(([g, a, b]) => ({ g, ...pool(e => e.air && e.log >= a && e.log <= b && e.profile === 1) }));
const lowHz = median(long.filter(w => w.profile === 1).map(w => w.headspeed)) / 60;
out.push(`**Second harmonics.** Only at profile 1 (${n(lowHz * 60, 0)} rpm) do both ${n(2 * target, 2)} × and 8 × fall below the logging limit of ${RULES.logLimitHz} Hz (${n(2 * target * lowHz, 0)} and ${n(8 * lowHz, 0)} Hz). ` +
    'A two-bladed rotor turning at a given rate shakes the airframe at twice that rate as well.', '');
results.harmonics = [];
out.push(...table(['Group', 'Windows', 'Line', 'Roll / pitch / yaw (deg/s)', 'Stands above its surroundings'], low.flatMap(({ g, m, w }) => [['the line', target], ['its double', 2 * target], ['4 ×', 4], ['8 ×', 8]].map(([name, o]) => { const v = lineAt(m, w, o);
    results.harmonics.push({ group: g, name, order: o, axes: v.axes, stands: v.stands }); return [g, w, `${name} (${n(o, 3)})`, v.axes.map(x => n(x, 2)).join(' / '), `${n(v.stands, 1)} ×`]; }))));
const pitchCorr = RULES.groups.slice(2).flatMap(([g, a, b]) => [1, 2, 3].map(p => { const list = short.filter(w => w.airborne > 0.95 && w.log >= a && w.log <= b && w.profile === p && w.tailServo !== null); if (list.length < 15) return null;
    return { g, p, windows: list.length, pitch: spearman(list.map(w => Math.abs(w.tailServo - RULES.tailCentre)), list.map(w => amp(w.line.axes))), collective: spearman(list.map(w => w.collective), list.map(w => amp(w.line.axes))) }; })).filter(Boolean);
results.pitchCorrelation = pitchCorr;
out.push(`**Tail blade pitch.** Rank correlation, window by window, between the size of the line and how far the tail servo stands from its centre (${RULES.tailCentre} µs), which sets tail blade pitch. A mismatch in pitch between the two tail blades grows with pitch; a mass imbalance does not.`, '');
out.push(...table(['Group', 'Profile', 'Windows', 'Against tail pitch', 'Against collective'], pitchCorr.map(c => [c.g, c.p, c.windows, n(c.pitch, 2), n(c.collective, 2)])));
results.shape = [];
const shapeRows = low.map(({ g, m, w }) => { const k0 = Math.round(target * scaleOf * R); let b = k0; for (let k = k0 - 3; k <= k0 + 3; k++) if (P(m, k) > P(m, b)) b = k;
    const db = (k) => 10 * Math.log10(P(m, k) / P(m, b)); let sh = null;
    for (let k = b - 20; k <= b + 20; k++) if (Math.abs(k - b) >= 3 && P(m, k) > P(m, k - 1) && P(m, k) > P(m, k + 1) && (sh === null || P(m, k) > P(m, sh))) sh = k;
    results.shape.push({ group: g, halfWidthBins: [1, 2, 3].map(j => (db(b - j) + db(b + j)) / 2), shoulder: sh === null ? null : { offset: (sh - b) / R, db: db(sh) } });
    return [g, w, [1, 2, 3].map(j => `${n(db(b + j), 0)} dB`).join(', '), sh === null ? '–' : `${n((sh - b) / R, 4)} × at ${n(db(sh), 0)} dB (${n(100 * Math.pow(10, db(sh) / 20), 0)} % of the line)`]; });
out.push('**A second line close by.** Two parts of slightly different size turning at nearly the same rate would show as a pair at a fixed spacing. Profile 1, all windows of a group summed (1 bin = 1/512 of rotor speed):', '');
out.push(...table(['Group', 'Windows', 'Fall-off 1, 2, 3 bins above the line', 'Largest shoulder within 20 bins'], shapeRows));
out.push('The line is as narrow as the window allows. The shoulder beside it moves between the groups, which a second part of fixed size would not do.', '');
const grow = (o) => { const pick = (g) => low.find(v => v.g === g); const a = lineAt(pick('#7–#16').m, pick('#7–#16').w, o), b = lineAt(pick('#17–#26').m, pick('#17–#26').w, o); return b.axes.map((v, i) => v / a.axes[i]); };
const growth = { line: grow(target), four: grow(4) };
results.growth = growth;
out.push(`**The blade change.** At profile 1, from #7–#16 to #17–#26, the line grew by ${growth.line.map(v => n(v, 1)).join(' / ')} (roll / pitch / yaw); the line at 4 × changed by ${growth.four.map(v => n(v, 1)).join(' / ')}.`, '');

H('## 5. Candidates');
out.push('The tail rotor turns at one ratio only, so only one of the two lines can be the tail rotor. Both lines can still be present together: a two-bladed main rotor makes its own 4th harmonic at exactly 4.00 × whatever pulley is fitted, and the log also has its 2 ×, 3 ×, 6 × and 7 ×. ' +
    'The question is therefore which of the two lines the tail rotor makes. Independent tests of that question, with adversarial checks, are in `which-line/README.md`.', '');
const rollerHit = 2 * all.se / target / RULES.rollerTolerance;
results.rollerChance = rollerHit;
const dEff = 76 * 2 / (Math.PI * target);
out.push('Each candidate predicts a fingerprint; the table sets it against the measurement.', '');
out.push(...table(['Candidate', 'It predicts', 'Measured', 'Verdict'], [
    ['Tail rotor, turning at 72/19 × main rotor', 'ratio exactly 72/19; no drift with load; on the ground too; harmonic at twice the rate; changes with tail blades', `${n(all.mean, 5)} ± ${n(all.se, 5)}; drift ≤ ${n(1e6 * Math.max(moves.blades, moves.collective, moves.servo) / target, 0)} ppm; on the ground ✓; double ✓, 8 × absent; grew ${growth.line.map(v => n(v, 1)).join('/')} × with the carbon blades`, 'fits every fingerprint. It needs a 72-tooth front pulley with the 19-tooth tail pulley; the manual and the configuration say 76'],
    ['Tail rotor at 4 × main rotor (76:19)', 'a line at exactly 4 ×', `a line at ${n(median(tailRatio), 5)} ×, 3 to 9 deg/s; no harmonic at 8 ×`, 'possible for the line at 4 ×; it does not explain the 72/19 line'],
    ['Tensioner roller, turned by the belt', `ratio = belt speed / roller circumference, any value; needs an effective diameter of ${n(dEff, 3)} mm; creeps with belt tension; two rollers give two lines`, `no drift with tail load; one line only`, `landing within ±2 standard errors of 72/19 by chance: about ${n(100 * rollerHit, 1)} % for a ±${n(100 * RULES.rollerTolerance, 1)} % spread of roller size; not excluded, not likely`],
    ['Main shaft bearings (4.77 × 12.7 × 5 mm)', 'ball-pass frequency moves with contact angle, i.e. with rotor thrust, by around 1 % over the collective range', `no move with collective beyond ${n(moves.collective, 5)}`, 'excluded'],
    ['Blade or rotor mode that scales with rotor speed', 'ratio moves when the blades change', `moved ${n(moves.blades, 5)} with the blade change`, 'excluded'],
    ['Aliasing of a rotor harmonic by the gyro sampling', 'a frequency that does not scale with rotor speed', 'same ratio at 3500, 4500 and 5000 rpm and on the ground', 'excluded'],
    ['Belt (850 mm, 425 teeth)', 'once per belt turn at 76/425 = 0.1788 (or 72/425 = 0.1694) and combinations with rotor lines', '72/19 − 4 = −4/19, which is no multiple of either', 'excluded as the source of this line'],
]));

H('## 6. What the flight controller does with it');
if (B && B.lines && B.lines.filter) {
    const passAt = (o) => B.lines.filter.reduce((best, f) => Math.abs(f.order - o) < Math.abs(best.order - o) ? f : best).passes;
    const foreign = B.lines.list.find(l => Math.abs(l.order - target) < 0.01);
    results.filter = { line: foreign ? foreign.filterPasses : null, notches: [1, 2, 4].map(o => ({ order: o, passes: passAt(o) })) };
    out.push(`The RPM filter notches the main rotor at 1 × and 2 × and the configured tail rotor at 4 ×. What reaches the PID loops (filtered over raw gyro, from \`bursts.json\`):`, '');
    out.push(...table(['Where', 'Roll', 'Pitch', 'Yaw'], [...[1, 2, 4].map(o => [`${o} × (notched)`, ...passAt(o).map(v => `${n(100 * v, 1)} %`)]), ...(foreign ? [[`${n(target, 3)} × (the line)`, ...foreign.filterPasses.map(v => `${n(100 * v, 0)} %`)]] : [])]));
    out.push(`Whatever its source, the line reaches the PID loops almost unfiltered, while a notch cuts the lines it sits on to under 1 %. At profile 3 it lies at ${n(target * 5000 / 60, 0)} Hz, above the dynamic notch's range (\`dyn_notch_max_hz = 240\`).`, '');
}

H('## 7. The test that decides');
out.push(...[
    'Mark one tail blade and a fixed point beside it. Turn the main rotor by hand exactly one turn, in its normal direction, and watch the tail:',
    '',
    `- **76:19**: the tail makes exactly 4 turns and the blade stops on its mark.`,
    `- **72:19**: the tail makes 3.79 turns and the blade stops ${n(360 * (4 - 72 / 19), 0)}° short of its mark.`,
    '',
    'Counting the teeth on the pulley on the main shaft answers the same question.',
    '',
    '- If the count is 72, the line is the tail rotor\'s own once-per-revolution vibration (mass imbalance: blades, grips, hub, tail shaft), which grew about threefold with the carbon tail blades. `tail_rotor_gear_ratio` would then be `19,72`, and the RPM filter\'s tail notch would sit on the line.',
    '- If the count is 76, the tail rotor turns at 4 × and the 72/19 line comes from a part this log cannot name. A tensioner roller of about 12.8 mm effective diameter is the next suspect.',
    '',
]);

fs.writeFileSync(path.join(DIR, 'line_report.md'), out.join('\n'));
fs.writeFileSync(path.join(DIR, 'line_results.json'), JSON.stringify(results, null, 1));
console.error(`wrote ${path.join(DIR, 'line_report.md')} and line_results.json`);
